"""[R] Render — produce the final PicksResponse JSON.

Takes the selected list (already ranked) and per-ticker pick payloads from
[H] Hypothesis and writes the day's `data/picks_<date>.json`. The middleware
reads this file directly; no further computation is needed at request time.

Now also carries the regime status and a top-level message (e.g. "Regime
HALTED" or "Nothing actionable today") so the UI can render the banner.
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Optional
from zoneinfo import ZoneInfo

IST = ZoneInfo("Asia/Kolkata")
_PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
_DATA_DIR = _PROJECT_ROOT / "data"
_DATA_DIR.mkdir(parents=True, exist_ok=True)

stage_id = "R"

# Top-level picks-response schema version. Bump this when adding fields to
# the response so cached picks_<date>.json files written by an older binary
# are auto-regenerated by catchup. v5 = single closest_to_firing dict
# replaces the near_misses / early_signals / ready_to_break trio.
PICKS_SCHEMA_VERSION = 5


def render_picks_response(
    selected_payloads: list[dict],
    today_iso: str,
    demo_mode: bool = False,
    regime: Optional[dict] = None,
    message: Optional[str] = None,
    closest_to_firing: Optional[dict] = None,
) -> dict:
    """Return a PicksResponse-shaped dict. Caller is responsible for writing.

    `closest_to_firing` is `{accumulation, breakout, overall}` — three
    already-ranked lists of up to 5 rows each with 4 fields per row. Only
    populated on zero-pick days; the UI shows it as a tabbed panel.
    """
    response: dict = {
        "date": today_iso,
        "generated_at": datetime.now(IST).isoformat(timespec="seconds"),
        "source": "pipeline",
        "demo_mode": demo_mode,
        "schema_version": PICKS_SCHEMA_VERSION,
        "picks": selected_payloads,
    }
    if regime is not None:
        response["regime"] = regime
    if message is not None:
        response["message"] = message
    if closest_to_firing and any(closest_to_firing.get(k) for k in ("accumulation", "breakout", "overall")):
        response["closest_to_firing"] = closest_to_firing
    return response


def write_picks_file(payload: dict) -> Path:
    p = _DATA_DIR / f"picks_{payload['date']}.json"
    p.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    return p
